UM_TEXT = { 'BG' => 'bag',
				'BIN' => 'bin',
				'BK' => 'bulk',
				'BOT' => 'bottle',
				'BU' => 'bunch',
				'BX' => 'box',
				'CS' => 'case',
				'CTN' => 'carton',
				'CU' => 'cup',
				'CUP' => 'cup',
				'DZ' => 'dozen',
				'EA' => 'each',
				'GAL' => 'gallon',
				'HD' => 'head',
				'LB' => 'pound',
				'PC' => 'piece',
				'PG' => 'package',
				'PKG' => 'package',
				'PT' => 'pint',
				'STK' => 'stalk',
				'SX' => 'sack',
				'TR' => 'tray'
				}
